name: Build and Publish

on:
  workflow_run:
    workflows: ["Test"]
    branches: [main]
    types:
      - completed
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Build Dependencies
        run: python -m pip install build django setuptools

      - name: Build a binary wheel and a source tarball
        run: python -m build --sdist --wheel --outdir dist/

      - uses: actions/upload-artifact@v2
        with:
          name: 'build-dist'
          path: dist/*

  upload:
    runs-on: ubuntu-latest
    needs: ['build']
    if: "github.event.release"
  
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: 'build-dist'
          path: dist

      - name: Publish a Python distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
